### ISSUE TITLE
Shuffle at load_data in homework 1

### ISSUE THREAD

**Issue by Luvata** [Luvata/CS330-Stanford-2019#3]
`shuffle` at [load_data](https://github.com/Luvata/CS330-Stanford-2019/blob/master/HW1/load_data.py#L116) ? 

Some options: 
1. `shuffle(encoding) + shuffle(retrieval)`? (shuffle separately, then concatenate)
2. `shuffle(encoding + retrieval)` (shuffle both together)
3. Others idea ?

Currently I'm using (2), there can be chance that `retrieval` samples labels are duplicated or not appear in `encoding` samples. IMO I think the prediction will not be biased since the model must learn to deal with duplication or novelty class in retrieval phase
Did I miss something ? 
 
[Edit 1] Newest commit is currently using options (2)
[Edit 2]

On paper MANN 
> Interestingly, the MANN displayed better than random guessing on the **first instance** within a class. Seemingly, it employed a strategy of educated guessing; if a particular sample produced a key that was a poor match to any of the bindings stored in external memory, then the network was less likely to choose the class labels associated with these stored bindings, and hence increased its probability of correctly guessing this new class on the first instance.

So it seems (1) is still correct

**Comment by slee01** [comment]
Thanks for sharing your good repo!

I'm not sure what I'm saying is correct, but I think we shouldn't include duplicate classes for each classification task because we assumed that our target problem was N-shot & K-way task.
I found out that the sample_batch function in your repo can assign the same label to different characters in a single task as follows:
[[[1. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [1. 0. 0. 0. 0.]].

I did this homework by labeling without duplication.
Unfortunately, I guess my result is also unreasonable because its output is almost 1.0 prediction accuracy. I guess my code has some problems related to requirements for task definition, such as mutually-exclusive condition. I appreciate it if you give me any opinion about my code(load_data.py) or results. Thanks in advance!

=======================================================================
```
import numpy as np
import os
import random
import tensorflow as tf
from scipy import misc

# load data.py: Contains code to load batches of images and labels


def get_images(paths, labels, nb_samples=None, shuffle=True):
    if nb_samples is not None:
        sampler = lambda x: random.sample(x, nb_samples)
    else:
        sampler = lambda x: x
    images_labels = [(i, os.path.join(path, image))
                     for i, path in zip(labels, paths)
                     for image in sampler(os.listdir(path))]
    if shuffle:
        random.shuffle(images_labels)

    return images_labels


def image_file_to_array(filename, dim_input):
    image = misc.imread(filename)
    image = image.reshape([dim_input])
    image = image.astype(np.float32) / 255.0
    image = 1.0 - image
    return image


def get_one_hot_vector(vector, one_hot_dim):
    one_hot_vector = np.zeros((vector.shape[0], one_hot_dim))

    index_vector = np.squeeze(vector).astype(int)
    one_hot_vector[np.arange(vector.shape[0]), index_vector] = 1

    return one_hot_vector

class DataGenerator(object):
    """
    Data Generator capable of generating batches of Omniglot data.
    A "class" is considered a class of omniglot digits.
    """
    def __init__(self, num_classes, num_samples_per_class, config={}):
        """
        Args:
            num_classes: Number of classes for classification (K-way)
            num_samples_per_class: num samples to generate per class in one batch
            batch_size: size of meta batch size (e.g. number of functions)
        """
        self.num_samples_per_class = num_samples_per_class
        self.num_classes = num_classes
        data_folder = config.get('data_folder', './omniglot_resized')
        self.img_size = config.get('img_size', (28, 28))
        self.dim_input = np.prod(self.img_size)
        self.dim_output = self.num_classes
        character_folders = [os.path.join(data_folder, family, character) for family in os.listdir(data_folder)
                             if os.path.isdir(os.path.join(data_folder, family))
                             for character in os.listdir(os.path.join(data_folder, family))
                             if os.path.isdir(os.path.join(data_folder, family, character))]

        random.seed(1)
        random.shuffle(character_folders)
        num_val = 100
        num_train = 1100
        self.metatrain_character_folders = character_folders[: num_train]
        self.metaval_character_folders = character_folders[
            num_train:num_train + num_val]
        self.metatest_character_folders = character_folders[
            num_train + num_val:]

    def sample_batch(self, batch_type, batch_size):
        if batch_type == "train":
            folders = self.metatrain_character_folders
        elif batch_type == "val":
            folders = self.metaval_character_folders
        else:
            folders = self.metatest_character_folders

        #############################
        #### YOUR CODE GOES HERE ####
        #############################

        all_image_batches, all_label_batches = [], []

        for _ in range(batch_size):
            folders_batch = random.sample(folders, self.num_classes)
            paths_labels_batch = get_images(paths=folders_batch,
                                            labels=np.arange(len(folders_batch)),   # [0, 1, ... , num_classes -1]
                                            nb_samples=self.num_samples_per_class,  # 1 + 1 = 2
                                            shuffle=False)  # {(label, path)}_{nb_samples * num_classes)


            paths_labels_batch = np.array(paths_labels_batch)

            labels_batch = np.array([x[0] for x in paths_labels_batch])
            labels_batch = get_one_hot_vector(labels_batch, self.num_classes)
            images_batch = np.array([image_file_to_array(x[1], self.dim_input) for x in paths_labels_batch])

            labels_batch = labels_batch.reshape(self.num_classes, self.num_samples_per_class, -1).swapaxes(0, 1)
            images_batch = images_batch.reshape(self.num_classes, self.num_samples_per_class, -1).swapaxes(0, 1)

            for i in range(labels_batch.shape[0]):
                np.random.shuffle(labels_batch[i])

            all_image_batches.append(images_batch)
            all_label_batches.append(labels_batch)

        all_image_batches = np.array(all_image_batches).reshape(batch_size,
                                                                self.num_samples_per_class,
                                                                self.num_classes,
                                                                self.dim_input)
        all_label_batches = np.array(all_label_batches).reshape(batch_size,
                                                                self.num_samples_per_class,
                                                                self.num_classes,
                                                                self.num_classes)

        return all_image_batches, all_label_batches

```

**Comment by Luvata** [comment]
Thank you @slee01 , you're right, my shuffle implementation is wrong with K way N shot task
I've changed it to (2): shuffle(train) + shuffle(test), there will be no duplicates on test set now

I think there might be some problem with your `load_data.py`
you can run this code to check your sample_batch (images on same row should be similar)

```python
from load_data import DataGenerator
import matplotlib.pyplot as plt


if __name__ == '__main__':
    generator = DataGenerator(5, 2)
    img_batches, labels_batches = generator.sample_batch("train", 1)

    labels = labels_batches[0]
    train_labels, test_labels = labels
    print(labels)

    train_imgs = img_batches[0][0]
    test_imgs  = img_batches[0][1]

    for i in range(5):
        train_loc = train_labels[:, i] == 1
        train_img = train_imgs[train_loc].reshape(28, 28)

        test_loc = test_labels[:, i] == 1
        print(train_loc, test_loc)
        test_img = test_imgs[test_loc].reshape(28, 28)

        plt.subplot(5, 2, i * 2 + 1)
        plt.axis('off')
        plt.imshow(train_img)

        plt.subplot(5, 2, i * 2 + 2)
        plt.axis('off')
        plt.imshow(test_img)
    plt.show()
```

**Comment by Luvata** [comment]
Sorry my code has some bug, I will investigate in your load_data soon

**Comment by Luvata** [comment]
Sorry for late reply, I was so busy recently

I haven't test your `load_data` yet, but I got a bug on training models, where I accidentally zero-out test_labels of last N data points (modifing when passing by reference). That's why my model has overwhelming test performance and also did bad when learning with correct `load_data`. You should take a look and double check it :eyes:

I also changed my `load_data` to shuffle(train) + shuffle(test), which I think is a correct way to train this model. I will refactor and also fixs my implementation in the next commit

**Comment by shivam-chandhok** [comment]
Hi Luvata,

Thank you for the homework code.
Even I am facing the problem that @slee01  is facing.
My network immediately gives a test accuracy=1.0.
Did this happen with you as well?
Do you have any idea what the reason might be?

**Comment by Luvata** [comment]
Hi @shivam-chandhok,
I suggest you double check two parts:
- 1. Check your `load_data`, you can use this [gist](https://gist.github.com/Luvata/eee3475220724bd449d15a0187060b54) to check, press Q to next
- 2. Double check `call` in `MANN`, make sure that you don't zero-out the last N value of `input_labels` (I used to stuck here because of this, and TF1 is not so friendly to debug :(( )

**Comment by shivam-chandhok** [comment]
Hi Luvata,

Thank you for your response.
Turns out that if I process data the way you do in load_data.py, it works.
Can you tell me why is it important to keep first example of every class for test set and then shuffle train and test separately before concatenating?

**Comment by Luvata** [comment]
It's just a way (a little hacky though) to make sure that test set also has the same number of classes as train set 

But I think the better way is using reshape similar to HW2 

Glad it help !
