### ISSUE TITLE
Is Homework 2 code complete?

### ISSUE THREAD

**Issue by shivam-chandhok** [Luvata/CS330-Stanford-2019#7]
Hi @Luvata

Is the code for HW2 also complete, if not will it be possible for you to upload the completed code.It will be of great help.

Thank You.

**Comment by Luvata** [comment]
I'm stuck at HW2, and recently I'm a little busy, so I'm not guarantee to have a clear deadline for it.

The stared code for HW2 did come with a better load_data, so you can take a look at stanford website
